package preprocessing

import (
	"encoding/json"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"testing"
)

// fixture mirrors the JSON structure written by fixtures/generate_scaler_fixtures.py.
type fixture struct {
	Description string      `json:"description"`
	X           [][]float64 `json:"X"`
	Mean        []float64   `json:"mean"`
	Scale       []float64   `json:"scale"`
	Var         []float64   `json:"var"`
	XScaled     [][]float64 `json:"X_scaled"`
	XInverse    [][]float64 `json:"X_inverse"`
}

func loadFixtures(t *testing.T) map[string]fixture {
	t.Helper()
	path := filepath.Join("testdata", "standard_scaler_fixtures.json")
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("failed to read fixtures at %s: %v", path, err)
	}
	var fixtures map[string]fixture
	if err := json.Unmarshal(data, &fixtures); err != nil {
		t.Fatalf("failed to parse fixtures: %v", err)
	}
	return fixtures
}

const floatTolerance = 1e-10

func assertClose(t *testing.T, name string, got, want float64) {
	t.Helper()
	if math.Abs(got-want) > floatTolerance {
		t.Errorf("%s: got %.10f, want %.10f (diff %.2e)", name, got, want, math.Abs(got-want))
	}
}

func assertSliceClose(t *testing.T, name string, got, want []float64) {
	t.Helper()
	if len(got) != len(want) {
		t.Fatalf("%s: length mismatch, got %d, want %d", name, len(got), len(want))
	}
	for i := range want {
		assertClose(t, fmt.Sprintf("%s[%d]", name, i), got[i], want[i])
	}
}

func assertMatrixClose(t *testing.T, name string, got, want [][]float64) {
	t.Helper()
	if len(got) != len(want) {
		t.Fatalf("%s: row count mismatch, got %d, want %d", name, len(got), len(want))
	}
	for i := range want {
		assertSliceClose(t, fmt.Sprintf("%s[%d]", name, i), got[i], want[i])
	}
}

// TestStandardScaler_AgainstSklearn runs every fixture generated by scikit-learn
// and checks that scikit-go's StandardScaler reproduces the same mean, scale, variance,
// transformed, and inverse-transformed output within tolerance.
func TestStandardScaler_AgainstSklearn(t *testing.T) {
	fixtures := loadFixtures(t)
	for name, fx := range fixtures {
		fx := fx
		t.Run(name, func(t *testing.T) {
			scaler := NewStandardScaler()
			if err := scaler.Fit(fx.X); err != nil {
				t.Fatalf("Fit failed: %v", err)
			}

			assertSliceClose(t, "mean", scaler.Mean, fx.Mean)
			assertSliceClose(t, "scale", scaler.Scale, fx.Scale)
			assertSliceClose(t, "var", scaler.Var, fx.Var)

			scaled, err := scaler.Transform(fx.X)
			if err != nil {
				t.Fatalf("Transform failed: %v", err)
			}
			assertMatrixClose(t, "X_scaled", scaled, fx.XScaled)

			fitScaled, err := scaler.FitTransform(fx.X)
			if err != nil {
				t.Fatalf("FitTransform failed: %v", err)
			}
			assertMatrixClose(t, "X_fit_transform", fitScaled, fx.XScaled)

			inverse, err := scaler.InverseTransform(scaled)
			if err != nil {
				t.Fatalf("InverseTransform failed: %v", err)
			}
			assertMatrixClose(t, "X_inverse", inverse, fx.XInverse)
		})
	}
}

func TestStandardScaler_TransformBeforeFit(t *testing.T) {
	scaler := NewStandardScaler()
	_, err := scaler.Transform([][]float64{{1.0, 2.0}})
	if err == nil {
		t.Fatal("Expected error when calling Transform before Fit, got nil")
	}
}

func TestStandardScaler_InverseTransformBeforeFit(t *testing.T) {
	scaler := NewStandardScaler()
	_, err := scaler.InverseTransform([][]float64{{1.0, 2.0}})
	if err == nil {
		t.Fatal("Expected error when calling InverseTransform before Fit, got nil")
	}
}

func TestStandardScaler_EmptyInput(t *testing.T) {
	scaler := NewStandardScaler()
	if err := scaler.Fit([][]float64{}); err == nil {
		t.Fatal("Expected error on empty input, got nil")
	}
	if err := scaler.Fit([][]float64{{}}); err == nil {
		t.Fatal("Expected error on empty row, got nil")
	}
}

func TestStandardScaler_RaggedInput(t *testing.T) {
	scaler := NewStandardScaler()
	X := [][]float64{{1.0, 2.0}, {3.0}} // ragged rows
	if err := scaler.Fit(X); err == nil {
		t.Fatal("Expected error on ragged input, got nil")
	}
}

func TestStandardScaler_NaNInput(t *testing.T) {
	scaler := NewStandardScaler()
	X := [][]float64{{1.0}, {math.NaN()}}
	if err := scaler.Fit(X); err == nil {
		t.Fatal("Expected error on NaN input, got nil")
	}
}

func TestStandardScaler_InfInput(t *testing.T) {
	scaler := NewStandardScaler()
	X := [][]float64{{1.0}, {math.Inf(1)}}
	if err := scaler.Fit(X); err == nil {
		t.Fatal("Expected error on Inf input, got nil")
	}
}

func TestStandardScaler_TransformWrongFeatureCount(t *testing.T) {
	scaler := NewStandardScaler()
	X := [][]float64{{1.0, 2.0}, {3.0, 4.0}}
	if err := scaler.Fit(X); err != nil {
		t.Fatalf("Fit failed: %v", err)
	}
	_, err := scaler.Transform([][]float64{{1.0, 2.0, 3.0}})
	if err == nil {
		t.Fatal("Expected error when Transform feature count mismatches training, got nil")
	}
}

func TestStandardScaler_SaveLoadRoundTrip(t *testing.T) {
	scaler := NewStandardScaler()
	X := [][]float64{{1.0, 2.0}, {2.0, 3.0}, {3.0, 4.0}, {4.0, 5.0}, {5.0, 6.0}}
	if err := scaler.Fit(X); err != nil {
		t.Fatalf("Fit failed: %v", err)
	}

	tmpFile := filepath.Join(t.TempDir(), "scaler.bin")
	if err := scaler.Save(tmpFile); err != nil {
		t.Fatalf("Save failed: %v", err)
	}

	loaded, err := LoadStandardScaler(tmpFile)
	if err != nil {
		t.Fatalf("LoadStandardScaler failed: %v", err)
	}

	assertSliceClose(t, "loaded.Mean", loaded.Mean, scaler.Mean)
	assertSliceClose(t, "loaded.Scale", loaded.Scale, scaler.Scale)
	assertSliceClose(t, "loaded.Var", loaded.Var, scaler.Var)

	orig, _ := scaler.Transform(X)
	loadedScaled, err := loaded.Transform(X)
	if err != nil {
		t.Fatalf("loaded scaler Transform failed: %v", err)
	}
	assertMatrixClose(t, "loaded transform", loadedScaled, orig)
}

func TestStandardScaler_SaveBeforeFit(t *testing.T) {
	scaler := NewStandardScaler()
	err := scaler.Save(filepath.Join(t.TempDir(), "scaler.bin"))
	if err == nil {
		t.Fatal("expected error saving unfitted scaler, got nil")
	}
}

func TestLoadStandardScaler_NonexistentFile(t *testing.T) {
	_, err := LoadStandardScaler("/nonexistent/path/scaler.bin")
	if err == nil {
		t.Fatal("expected error loading nonexistent file, got nil")
	}
}
