package linear

import (
	"encoding/json"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"testing"
)

// Fixture mirrors the JSON structure written by fixtures/generate_fixtures.py.
type fixture struct {
	Description string      `json:"description"`
	X           [][]float64 `json:"X"`
	Y           []float64   `json:"y"`
	Coef        []float64   `json:"coef"`
	Intercept   float64     `json:"intercept"`
	Predictions []float64   `json:"predictions"`
	R2Score     float64     `json:"r2_score"`
}

func loadFixtures(t *testing.T) map[string]fixture {
	t.Helper()
	path := filepath.Join("testdata", "linear_regression_fixtures.json")
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("failed to read fixtures at %s: %v", path, err)
	}
	var fixtures map[string]fixture
	if err := json.Unmarshal(data, &fixtures); err != nil {
		t.Fatalf("failed to parse fixtures: %v", err)
	}
	return fixtures
}

const floatTolerance = 1e-6

func assertClose(t *testing.T, name string, got, want float64) {
	t.Helper()
	if math.Abs(got-want) > floatTolerance {
		t.Errorf("%s: got %.10f, want %.10f (diff %.2e)", name, got, want, math.Abs(got-want))
	}
}

func assertSliceClose(t *testing.T, name string, got, want []float64) {
	t.Helper()
	if len(got) != len(want) {
		t.Fatalf("%s: length mismatch, got %d, want %d", name, len(got), len(want))
	}
	for i := range want {
		assertClose(t, fmt.Sprintf("%s[%d]", name, i), got[i], want[i])
	}
}

// TestLinearRegression_AgainstSklearn runs every fixture generated by scikit-learn and checks that scikit-go's LinearRegression reproduces the same coefficients, intercept, predictions, and R^2 within tolerance.
func TestLinearRegression_AgainstSklearn(t *testing.T) {
	fixtures := loadFixtures(t)
	for name, fx := range fixtures {
		fx := fx
		t.Run(name, func(t *testing.T) {
			model := NewLinearRegression()
			if err := model.Fit(fx.X, fx.Y); err != nil {
				t.Fatalf("Fit failed: %v", err)
			}

			assertSliceClose(t, "coef", model.Coef, fx.Coef)
			assertClose(t, "intercept", model.Intercept, fx.Intercept)
			preds, err := model.Predict(fx.X)
			if err != nil {
				t.Fatalf("Predict failed: %v", err)
			}
			assertSliceClose(t, "predictions", preds, fx.Predictions)
			r2, err := model.Score(fx.X, fx.Y)
			if err != nil {
				t.Fatalf("Score failed: %v", err)
			}
			assertClose(t, "r2_score", r2, fx.R2Score)
		})
	}
}

func TestLinearRegression_PredictBeforeFit(t *testing.T) {
	model := NewLinearRegression()
	_, err := model.Predict([][]float64{{1.0, 2.0}})
	if err == nil {
		t.Fatal("Expected error when calling Predict before Fit, got nil")
	}
}

func TestLinearRegression_EmptyInput(t *testing.T) {
	model := NewLinearRegression()
	if err := model.Fit([][]float64{}, []float64{}); err == nil {
		t.Fatal("Expected error on empty input, got nil")
	}
}

func TestLinearRegression_MismatchedDimensions(t *testing.T) {
	model := NewLinearRegression()
	X := [][]float64{{1.0}, {2.0}}
	y := []float64{1.0, 2.0, 3.0} // mismatched length
	if err := model.Fit(X, y); err == nil {
		t.Fatal("Expected error on mismatched X/y dimensions, got nil")
	}
}

func TestLinearRegression_RaggedInput(t *testing.T) {
	model := NewLinearRegression()
	X := [][]float64{{1.0, 2.0}, {3.0}} // ragged rows
	y := []float64{1.0, 2.0}
	if err := model.Fit(X, y); err == nil {
		t.Fatal("Expected error on ragged input, got nil")
	}
}

func TestLinearRegression_NaNInput(t *testing.T) {
	model := NewLinearRegression()
	X := [][]float64{{1.0}, {math.NaN()}}
	y := []float64{1.0, 2.0}
	if err := model.Fit(X, y); err == nil {
		t.Fatal("Expected error on NaN input, got nil")
	}
}

func TestLinearRegression_PredictWrongFeatureCount(t *testing.T) {
	model := NewLinearRegression()
	X := [][]float64{{1.0, 2.0}, {2.0, 3.0}, {3.0, 5.0}}
	y := []float64{1.0, 2.0, 3.0}
	if err := model.Fit(X, y); err != nil {
		t.Fatalf("Fit failed: %v", err)
	}
	_, err := model.Predict([][]float64{{1.0, 2.0, 3.0}})
	if err == nil {
		t.Fatal("Expected error when Predict feature count mismatches training, got nil")
	}
}

func TestLinearRegression_ScoreConstantTargets(t *testing.T) {
	// On constant targets R2 follows sklearn's edge rules (ssTot == 0): predictions
	// not bitwise equal to the constant score 0.0, perfect predictions score 1.0.
	// This guards the Score delegation to metrics.R2Score.
	model := NewLinearRegression()
	X := [][]float64{{1.0}, {2.0}, {3.0}}
	constY := []float64{5.0, 5.0, 5.0}
	if err := model.Fit(X, constY); err != nil {
		t.Fatalf("Fit failed: %v", err)
	}

	// QR lstsq returns intercept/coef with tiny floating-point residuals, so
	// predictions are never bitwise equal to the constant -> sklearn scores 0.0.
	r2, err := model.Score(X, constY)
	if err != nil {
		t.Fatalf("Score failed: %v", err)
	}
	if r2 != 0.0 {
		t.Errorf("constant-target fit: got %v, want 0.0", r2)
	}
}

func TestLinearRegression_ScoreExactFit(t *testing.T) {
	// y = 2x + 1 is reproduced exactly, so R2 is ~1.0.
	model := NewLinearRegression()
	X := [][]float64{{1.0}, {2.0}, {3.0}, {4.0}, {5.0}}
	y := []float64{3.0, 5.0, 7.0, 9.0, 11.0}
	if err := model.Fit(X, y); err != nil {
		t.Fatalf("Fit failed: %v", err)
	}
	r2, err := model.Score(X, y)
	if err != nil {
		t.Fatalf("Score failed: %v", err)
	}
	if math.Abs(r2-1.0) > 1e-10 {
		t.Errorf("exact-fit R2: got %v, want ~1.0", r2)
	}
}

func TestLinearRegression_SaveLoadRoundTrip(t *testing.T) {
	model := NewLinearRegression()
	X := [][]float64{{1.0}, {2.0}, {3.0}, {4.0}, {5.0}}
	y := []float64{3.0, 5.0, 7.0, 9.0, 11.0} // y = 2x + 1

	if err := model.Fit(X, y); err != nil {
		t.Fatalf("Fit failed: %v", err)
	}

	tmpFile := filepath.Join(t.TempDir(), "model.bin")
	if err := model.Save(tmpFile); err != nil {
		t.Fatalf("Save failed: %v", err)
	}

	loaded, err := LoadLinearRegression(tmpFile)
	if err != nil {
		t.Fatalf("LoadLinearRegression failed: %v", err)
	}

	assertSliceClose(t, "loaded.Coef", loaded.Coef, model.Coef)
	assertClose(t, "loaded.Intercept", loaded.Intercept, model.Intercept)

	origPreds, _ := model.Predict(X)
	loadedPreds, err := loaded.Predict(X)
	if err != nil {
		t.Fatalf("loaded model Predict failed: %v", err)
	}
	assertSliceClose(t, "loaded predictions", loadedPreds, origPreds)
}

func TestLinearRegression_SaveBeforeFit(t *testing.T) {
	model := NewLinearRegression()
	err := model.Save(filepath.Join(t.TempDir(), "model.bin"))
	if err == nil {
		t.Fatal("expected error saving unfitted model, got nil")
	}
}

func TestLoadLinearRegression_NonexistentFile(t *testing.T) {
	_, err := LoadLinearRegression("/nonexistent/path/model.bin")
	if err == nil {
		t.Fatal("expected error loading nonexistent file, got nil")
	}
}
