package linear

import (
	"encoding/json"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"testing"
)

// Fixture mirrors the JSON structure written by fixtures/generate_fixtures.py.
type fixture struct {
	Description string      `json:"description"`
	X           [][]float64 `json:"X"`
	Y           []float64   `json:"y"`
	Coef        []float64   `json:"coef"`
	Intercept   float64     `json:"intercept"`
	Predictions []float64   `json:"predictions"`
	R2Score     float64     `json:"r2_score"`
}

func loadFixtures(t *testing.T) map[string]fixture {
	t.Helper()
	path := filepath.Join("testdata", "linear_regression_fixtures.json")
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("failed to read fixtures at %s: %v", path, err)
	}
	var fixtures map[string]fixture
	if err := json.Unmarshal(data, &fixtures); err != nil {
		t.Fatalf("failed to parse fixtures: %v", err)
	}
	return fixtures
}

const floatTolerance = 1e-6

func assertClose(t *testing.T, name string, got, want float64) {
	t.Helper()
	if math.Abs(got-want) > floatTolerance {
		t.Errorf("%s: got %.10f, want %.10f (diff %.2e)", name, got, want, math.Abs(got-want))
	}
}

func assertSliceClose(t *testing.T, name string, got, want []float64) {
	t.Helper()
	if len(got) != len(want) {
		t.Fatalf("%s: length mismatch, got %d, want %d", name, len(got), len(want))
	}
	for i := range want {
		assertClose(t, fmt.Sprintf("%s[%d]", name, i), got[i], want[i])
	}
}

// TestLinearRegression_AgainstSklearn runs every fixture generated by scikit-learn and checks that scikit-go's LinearRegression reproduces the same coefficients, intercept, predictions, and R^2 within tolerance.
func TestLinearRegression_AgainstSklearn(t *testing.T) {
	fixtures := loadFixtures(t)
	for name, fx := range fixtures {
		fx := fx
		t.Run(name, func(t *testing.T) {
			model := NewLinearRegression()
			if err := model.Fit(fx.X, fx.Y); err != nil {
				t.Fatalf("Fit failed: %v", err)
			}

			assertSliceClose(t, "coef", model.Coef, fx.Coef)
			assertClose(t, "intercept", model.Intercept, fx.Intercept)
			preds, err := model.Predict(fx.X)
			if err != nil {
				t.Fatalf("Predict failed: %v", err)
			}
			assertSliceClose(t, "predictions", preds, fx.Predictions)
			r2, err := model.Score(fx.X, fx.Y)
			if err != nil {
				t.Fatalf("Score failed: %v", err)
			}
			assertClose(t, "r2_score", r2, fx.R2Score)
		})
	}
}

func TestLinearRegression_PredictBeforeFit(t *testing.T) {
	model := NewLinearRegression()
	_, err := model.Predict([][]float64{{1.0, 2.0}})
	if err == nil {
		t.Fatal("Expected error when calling Predict before Fit, got nil")
	}
}

func TestLinearRegression_EmptyInput(t *testing.T) {
	model := NewLinearRegression()
	if err := model.Fit([][]float64{}, []float64{}); err == nil {
		t.Fatal("Expected error on empty input, got nil")
	}
}

func TestLinearRegression_MismatchedDimensions(t *testing.T) {
	model := NewLinearRegression()
	X := [][]float64{{1.0}, {2.0}}
	y := []float64{1.0, 2.0, 3.0} // mismatched length
	if err := model.Fit(X, y); err == nil {
		t.Fatal("Expected error on mismatched X/y dimensions, got nil")
	}
}

func TestLinearRegression_RaggedInput(t *testing.T) {
	model := NewLinearRegression()
	X := [][]float64{{1.0, 2.0}, {3.0}} // ragged rows
	y := []float64{1.0, 2.0}
	if err := model.Fit(X, y); err == nil {
		t.Fatal("Expected error on ragged input, got nil")
	}
}

func TestLinearRegression_NaNInput(t *testing.T) {
	model := NewLinearRegression()
	X := [][]float64{{1.0}, {math.NaN()}}
	y := []float64{1.0, 2.0}
	if err := model.Fit(X, y); err == nil {
		t.Fatal("Expected error on NaN input, got nil")
	}
}

func TestLinearRegression_PredictWrongFeatureCount(t *testing.T) {
	model := NewLinearRegression()
	X := [][]float64{{1.0, 2.0}, {2.0, 3.0}, {3.0, 5.0}}
	y := []float64{1.0, 2.0, 3.0}
	if err := model.Fit(X, y); err != nil {
		t.Fatalf("Fit failed: %v", err)
	}
	_, err := model.Predict([][]float64{{1.0, 2.0, 3.0}})
	if err == nil {
		t.Fatal("Expected error when Predict feature count mismatches training, got nil")
	}
}

func TestLinearRegression_ScoreConstantTargets(t *testing.T) {
	// On constant targets R2 follows sklearn's edge rules (ssTot == 0): predictions
	// not bitwise equal to the constant score 0.0, perfect predictions score 1.0.
	// This guards the Score delegation to metrics.R2Score.
	X := [][]float64{{1.0}, {2.0}, {3.0}}
	constY := []float64{5.0, 5.0, 5.0}

	// Fitting a constant target gives coef exactly 0 and intercept exactly 5, so
	// the predictions are exact and the score is 1.0 (as in sklearn).
	exact := NewLinearRegression()
	if err := exact.Fit(X, constY); err != nil {
		t.Fatalf("Fit failed: %v", err)
	}
	r2, err := exact.Score(X, constY)
	if err != nil {
		t.Fatalf("Score failed: %v", err)
	}
	if r2 != 1.0 {
		t.Errorf("exact fit on constant targets: got %v, want 1.0", r2)
	}

	// A model fitted to something else, scored against constant targets, is
	// not a perfect fit and scores 0.0.
	other := NewLinearRegression()
	if err := other.Fit(X, []float64{1, 2, 4}); err != nil {
		t.Fatalf("Fit failed: %v", err)
	}
	r2, err = other.Score(X, constY)
	if err != nil {
		t.Fatalf("Score failed: %v", err)
	}
	if r2 != 0.0 {
		t.Errorf("imperfect fit on constant targets: got %v, want 0.0", r2)
	}
}

// The minimum-norm solution must be returned (as sklearn does) instead of an
// error or a panic when the design matrix is rank deficient. Expected values come
// from sklearn.linear_model.LinearRegression.
func TestLinearRegression_RankDeficient(t *testing.T) {
	cases := []struct {
		name          string
		X             [][]float64
		y             []float64
		coef          []float64
		intercept     float64
		rank          int
		wantPredTrain []float64
	}{
		{"collinear columns", [][]float64{{1, 2}, {2, 4}, {3, 6}, {4, 8}}, []float64{1, 2, 3, 4},
			[]float64{0.2, 0.4}, 0, 1, []float64{1, 2, 3, 4}},
		{"more features than samples", [][]float64{{1, 2, 3}, {2, 1, 0}}, []float64{1, 2},
			[]float64{0.090909090909, -0.090909090909, -0.272727272727}, 1.909090909091, 1,
			[]float64{1, 2}},
		{"constant column", [][]float64{{1, 5}, {2, 5}, {3, 5}}, []float64{2, 4, 7},
			[]float64{2.5, 0}, -0.666666666667, 1, []float64{1.833333333333, 4.333333333333, 6.833333333333}},
		{"single sample", [][]float64{{2, 3}}, []float64{5},
			[]float64{0, 0}, 5, 0, []float64{5}},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			m := NewLinearRegression()
			if err := m.Fit(tc.X, tc.y); err != nil {
				t.Fatalf("Fit: %v", err)
			}
			for j, want := range tc.coef {
				if math.Abs(m.Coef[j]-want) > 1e-9 {
					t.Errorf("coef[%d]: got %v, want %v", j, m.Coef[j], want)
				}
			}
			if math.Abs(m.Intercept-tc.intercept) > 1e-9 {
				t.Errorf("intercept: got %v, want %v", m.Intercept, tc.intercept)
			}
			if m.Rank() != tc.rank {
				t.Errorf("rank: got %d, want %d", m.Rank(), tc.rank)
			}
			pred, err := m.Predict(tc.X)
			if err != nil {
				t.Fatalf("Predict: %v", err)
			}
			for i, want := range tc.wantPredTrain {
				if math.Abs(pred[i]-want) > 1e-9 {
					t.Errorf("pred[%d]: got %v, want %v", i, pred[i], want)
				}
			}
		})
	}
}

func TestLinearRegression_TolControlsRank(t *testing.T) {
	// The second column is a tiny perturbation of the first: with the default
	// tol=1e-6 it counts as collinear (rank 1); with a much smaller tol it does not.
	X := [][]float64{{1, 1 + 1e-9}, {2, 2 - 1e-9}, {3, 3 + 2e-9}, {4, 4}}
	y := []float64{1, 2, 3, 4}
	def := NewLinearRegression()
	if err := def.Fit(X, y); err != nil {
		t.Fatalf("Fit: %v", err)
	}
	strict := NewLinearRegression()
	strict.Tol = 1e-15
	if err := strict.Fit(X, y); err != nil {
		t.Fatalf("Fit: %v", err)
	}
	if def.Rank() != 1 || strict.Rank() != 2 {
		t.Errorf("rank: default tol %d (want 1), tol=1e-15 %d (want 2)", def.Rank(), strict.Rank())
	}

	bad := NewLinearRegression()
	bad.Tol = -1
	if err := bad.Fit(X, y); err == nil {
		t.Error("a negative tol should be rejected")
	}
	if NewLinearRegression().Rank() != 0 {
		t.Error("Rank before Fit should be 0")
	}
}

func TestLinearRegression_ScoreExactFit(t *testing.T) {
	// y = 2x + 1 is reproduced exactly, so R2 is ~1.0.
	model := NewLinearRegression()
	X := [][]float64{{1.0}, {2.0}, {3.0}, {4.0}, {5.0}}
	y := []float64{3.0, 5.0, 7.0, 9.0, 11.0}
	if err := model.Fit(X, y); err != nil {
		t.Fatalf("Fit failed: %v", err)
	}
	r2, err := model.Score(X, y)
	if err != nil {
		t.Fatalf("Score failed: %v", err)
	}
	if math.Abs(r2-1.0) > 1e-10 {
		t.Errorf("exact-fit R2: got %v, want ~1.0", r2)
	}
}

func TestLinearRegression_SaveLoadRoundTrip(t *testing.T) {
	model := NewLinearRegression()
	X := [][]float64{{1.0}, {2.0}, {3.0}, {4.0}, {5.0}}
	y := []float64{3.0, 5.0, 7.0, 9.0, 11.0} // y = 2x + 1

	if err := model.Fit(X, y); err != nil {
		t.Fatalf("Fit failed: %v", err)
	}

	tmpFile := filepath.Join(t.TempDir(), "model.bin")
	if err := model.Save(tmpFile); err != nil {
		t.Fatalf("Save failed: %v", err)
	}

	loaded, err := LoadLinearRegression(tmpFile)
	if err != nil {
		t.Fatalf("LoadLinearRegression failed: %v", err)
	}

	assertSliceClose(t, "loaded.Coef", loaded.Coef, model.Coef)
	assertClose(t, "loaded.Intercept", loaded.Intercept, model.Intercept)

	origPreds, _ := model.Predict(X)
	loadedPreds, err := loaded.Predict(X)
	if err != nil {
		t.Fatalf("loaded model Predict failed: %v", err)
	}
	assertSliceClose(t, "loaded predictions", loadedPreds, origPreds)
}

func TestLinearRegression_SaveBeforeFit(t *testing.T) {
	model := NewLinearRegression()
	err := model.Save(filepath.Join(t.TempDir(), "model.bin"))
	if err == nil {
		t.Fatal("expected error saving unfitted model, got nil")
	}
}

func TestLoadLinearRegression_NonexistentFile(t *testing.T) {
	_, err := LoadLinearRegression("/nonexistent/path/model.bin")
	if err == nil {
		t.Fatal("expected error loading nonexistent file, got nil")
	}
}
